"""Update sessions table for Ikigai

Revision ID: 97caa26d93fb
Revises: 5260bdb10656
Create Date: 2026-02-21 12:29:24.445799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97caa26d93fb'
down_revision: Union[str, Sequence[str], None] = '5260bdb10656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('careerprofile_test_sessions', sa.Column('persona_type', sa.String(length=20), nullable=False))
    op.add_column('careerprofile_test_sessions', sa.Column('test_goal', sa.String(length=20), nullable=False))
    op.add_column('careerprofile_test_sessions', sa.Column('target_profession_id', sa.BigInteger(), nullable=True))
    op.add_column('careerprofile_test_sessions', sa.Column('uses_ikigai', sa.Boolean(), nullable=False))
    op.add_column('careerprofile_test_sessions', sa.Column('algorithm_version', sa.String(length=20), nullable=True))
    op.add_column('careerprofile_test_sessions', sa.Column('question_set_version', sa.String(length=20), nullable=True))
    op.alter_column('careerprofile_test_sessions', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               nullable=False)
    op.alter_column('careerprofile_test_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('careerprofile_test_sessions', 'riasec_completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('careerprofile_test_sessions', 'ikigai_completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('careerprofile_test_sessions', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_index('idx_careerprofile_sessions_status', 'careerprofile_test_sessions', ['status'], unique=False)
    op.create_index('idx_careerprofile_sessions_token', 'careerprofile_test_sessions', ['session_token'], unique=False)
    op.create_index('idx_careerprofile_sessions_user_id', 'careerprofile_test_sessions', ['user_id'], unique=False)
    op.alter_column('riasec_codes', 'riasec_description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('riasec_codes', 'congruent_code_ids')
    op.drop_column('riasec_codes', 'updated_at')
    op.add_column('riasec_results', sa.Column('riasec_code_type', sa.String(length=20), nullable=False))
    op.alter_column('riasec_results', 'is_inconsistent_profile',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index('idx_riasec_results_session', 'riasec_results', ['test_session_id'], unique=False)
    op.drop_column('riasec_results', 'classification_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riasec_results', sa.Column('classification_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_index('idx_riasec_results_session', table_name='riasec_results')
    op.alter_column('riasec_results', 'is_inconsistent_profile',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('riasec_results', 'riasec_code_type')
    op.add_column('riasec_codes', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('riasec_codes', sa.Column('congruent_code_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('riasec_codes', 'riasec_description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index('idx_careerprofile_sessions_user_id', table_name='careerprofile_test_sessions')
    op.drop_index('idx_careerprofile_sessions_token', table_name='careerprofile_test_sessions')
    op.drop_index('idx_careerprofile_sessions_status', table_name='careerprofile_test_sessions')
    op.alter_column('careerprofile_test_sessions', 'completed_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('careerprofile_test_sessions', 'ikigai_completed_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('careerprofile_test_sessions', 'riasec_completed_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('careerprofile_test_sessions', 'started_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('careerprofile_test_sessions', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('careerprofile_test_sessions', 'question_set_version')
    op.drop_column('careerprofile_test_sessions', 'algorithm_version')
    op.drop_column('careerprofile_test_sessions', 'uses_ikigai')
    op.drop_column('careerprofile_test_sessions', 'target_profession_id')
    op.drop_column('careerprofile_test_sessions', 'test_goal')
    op.drop_column('careerprofile_test_sessions', 'persona_type')
    # ### end Alembic commands ###
