"""initial migration

Revision ID: 995c97fff635
Revises: 
Create Date: 2025-12-19 21:22:14.364039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '995c97fff635'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kenalidiri_categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detail_table_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_code')
    )
    op.create_index('idx_kenalidiri_categories_active', 'kenalidiri_categories', ['is_active'], unique=False)
    op.create_index('idx_kenalidiri_categories_code', 'kenalidiri_categories', ['category_code'], unique=False)
    op.create_table('riasec_codes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('riasec_code', sa.String(length=3), nullable=False),
    sa.Column('riasec_title', sa.String(length=255), nullable=False),
    sa.Column('riasec_description', sa.Text(), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('challenges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strategies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('work_environments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interaction_styles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('congruent_code_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("riasec_code ~ '^[RIASEC]{1,3}$'", name='chk_riasec_code_format'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('riasec_code')
    )
    op.create_table('ikigai_candidate_professions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('test_session_id', sa.BigInteger(), nullable=False),
    sa.Column('candidates_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['test_session_id'], ['careerprofile_test_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_session_id')
    )
    op.create_table('kenalidiri_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('test_category_id', sa.BigInteger(), nullable=False),
    sa.Column('detail_session_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['test_category_id'], ['kenalidiri_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kenalidiri_history_category_id', 'kenalidiri_history', ['test_category_id'], unique=False)
    op.create_index('idx_kenalidiri_history_started_at', 'kenalidiri_history', ['started_at'], unique=False)
    op.create_index('idx_kenalidiri_history_status', 'kenalidiri_history', ['status'], unique=False)
    op.create_index('idx_kenalidiri_history_user_id', 'kenalidiri_history', ['user_id'], unique=False)
    op.create_table('riasec_question_sets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('test_session_id', sa.BigInteger(), nullable=False),
    sa.Column('question_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['test_session_id'], ['careerprofile_test_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_session_id')
    )
    op.create_table('riasec_responses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('test_session_id', sa.BigInteger(), nullable=False),
    sa.Column('responses_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['test_session_id'], ['careerprofile_test_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_session_id')
    )
    op.create_table('riasec_results',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('test_session_id', sa.BigInteger(), nullable=False),
    sa.Column('score_r', sa.Integer(), nullable=False),
    sa.Column('score_i', sa.Integer(), nullable=False),
    sa.Column('score_a', sa.Integer(), nullable=False),
    sa.Column('score_s', sa.Integer(), nullable=False),
    sa.Column('score_e', sa.Integer(), nullable=False),
    sa.Column('score_c', sa.Integer(), nullable=False),
    sa.Column('riasec_code_id', sa.BigInteger(), nullable=False),
    sa.Column('classification_type', sa.String(length=20), nullable=False),
    sa.Column('is_inconsistent_profile', sa.Boolean(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("classification_type IN ('single', 'dual', 'triple')", name='chk_riasec_results_classification'),
    sa.CheckConstraint('score_r BETWEEN 2 AND 10 AND score_i BETWEEN 2 AND 10 AND score_a BETWEEN 2 AND 10 AND score_s BETWEEN 2 AND 10 AND score_e BETWEEN 2 AND 10 AND score_c BETWEEN 2 AND 10', name='chk_riasec_results_scores'),
    sa.ForeignKeyConstraint(['riasec_code_id'], ['riasec_codes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_session_id'], ['careerprofile_test_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('riasec_results')
    op.drop_table('riasec_responses')
    op.drop_table('riasec_question_sets')
    op.drop_index('idx_kenalidiri_history_user_id', table_name='kenalidiri_history')
    op.drop_index('idx_kenalidiri_history_status', table_name='kenalidiri_history')
    op.drop_index('idx_kenalidiri_history_started_at', table_name='kenalidiri_history')
    op.drop_index('idx_kenalidiri_history_category_id', table_name='kenalidiri_history')
    op.drop_table('kenalidiri_history')
    op.drop_table('ikigai_candidate_professions')
    op.drop_table('riasec_codes')
    op.drop_index('idx_kenalidiri_categories_code', table_name='kenalidiri_categories')
    op.drop_index('idx_kenalidiri_categories_active', table_name='kenalidiri_categories')
    op.drop_table('kenalidiri_categories')
    op.drop_table('careerprofile_test_sessions')
    # ### end Alembic commands ###
